name: hashcrypt
description: Hashcrypt.io is a utility tool for various Hashing and Encryption techniques.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.1.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  layout: ^0.6.2
  flutter_svg: ^1.1.6
  particles_fly: ^0.0.8
  hashlib: ^1.12.0
  dropdown_button2: ^1.9.2
  url_launcher: ^6.0.12
  font_awesome_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: VisueltPro
    fonts:
      - asset: assets/fonts/visuelt/VisueltPro-Thin.ttf
        weight: 100
      - asset: assets/fonts/visuelt/VisueltPro-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/visuelt/VisueltPro-Light.ttf
        weight: 300
      - asset: assets/fonts/visuelt/VisueltPro-Regular.ttf
        weight: 400
      - asset: assets/fonts/visuelt/VisueltPro-Medium.ttf
        weight: 500
      - asset: assets/fonts/visuelt/VisueltPro-Black.ttf
        weight: 700
      - asset: assets/fonts/visuelt/VisueltPro-Bold.ttf
        weight: 800